WORD_TYPES = [
    {
        "key": "noun",
        "table": "dict_noun",
        "zh": "名词",
        "en": "Noun",
        "abbr": "n.",
        "group": "实词",
    },
    {
        "key": "verb",
        "table": "dict_verb",
        "zh": "动词",
        "en": "Verb",
        "abbr": "v.",
        "group": "实词",
    },
    {
        "key": "adjective",
        "table": "dict_adjective",
        "zh": "形容词",
        "en": "Adjective",
        "abbr": "adj.",
        "group": "实词",
    },
    {
        "key": "numeral",
        "table": "dict_numeral",
        "zh": "数词",
        "en": "Numeral",
        "abbr": "num.",
        "group": "实词",
    },
    {
        "key": "classifier",
        "table": "dict_classifier",
        "zh": "量词",
        "en": "Classifier / Measure word",
        "abbr": "mw.",
        "group": "实词",
    },
    {
        "key": "pronoun",
        "table": "dict_pronoun",
        "zh": "代词",
        "en": "Pronoun",
        "abbr": "pron.",
        "group": "实词",
    },
    {
        "key": "adverb",
        "table": "dict_adverb",
        "zh": "副词",
        "en": "Adverb",
        "abbr": "adv.",
        "group": "虚词",
    },
    {
        "key": "preposition",
        "table": "dict_preposition",
        "zh": "介词",
        "en": "Preposition",
        "abbr": "prep.",
        "group": "虚词",
    },
    {
        "key": "conjunction",
        "table": "dict_conjunction",
        "zh": "连词",
        "en": "Conjunction",
        "abbr": "conj.",
        "group": "虚词",
    },
    {
        "key": "particle",
        "table": "dict_particle",
        "zh": "助词",
        "en": "Particle",
        "abbr": "part.",
        "group": "虚词",
    },
    {
        "key": "interjection",
        "table": "dict_interjection",
        "zh": "叹词",
        "en": "Interjection",
        "abbr": "interj.",
        "group": "虚词",
    },
    {
        "key": "onomatopoeia",
        "table": "dict_onomatopoeia",
        "zh": "拟声词",
        "en": "Onomatopoeia",
        "abbr": "ono.",
        "group": "虚词",
    },
]

WORD_TYPE_BY_KEY = {item["key"]: item for item in WORD_TYPES}
